spring:
  application:
    name: api

  datasource:
    url: jdbc:mysql://localhost/vollmed_api
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}